config/routes.rb
Rails.application.routes.draw do
  resources :guitarcats
  resources :categories
  resources :profiles
  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'
  
  
  
  resources :orders do
    resources:orderitems
  end
  
  
  
  
  
  
  
  devise_for :users do
    resources:orders
  end
    
    post '/search' => 'items#search'
    
    
    get '/checkout' => 'cart#createOrder'
  
  
  get 'cart/index'
  resources :items
  root 'static_pages#home'
  
  
  get '/about' =>'static_pages#about'
  get '/help' =>'static_pages#help'
  
  get '/login' => 'user#login'
  
  get '/logout' => 'user#logout'
  
  get '/cart/clear' => 'cart#clearCart'
  
  get '/cart/:id' => 'cart#add'
  
  get '/cart/remove/:id' => 'cart#remove'
  
  get '/cart/decrease/:id' => 'cart#decrease'
  
  get '/paid/:id' => 'static_pages#paid'
  
  get '/category/:title' => 'static_pages#category'
  
  get '/cart' => 'cart#index'
  

  
  # get 'static_pages/home'
  # get 'static_pages/help'
  # get 'static_pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  
    
    def order_params
      
    params.require(:order).permit(:order_date, :user_id, :status)  
        
    end
    
    has_many :orderitems    
  belongs_to :user
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  
  # GET /orders
  # GET /orders.json
  def index
   if user_signed_in? 
    @user = User.find(current_user.id)
    @orders = @user.orders.all
  
   else 
    redirect_to :root
   end 
  end
  
  
  

  # GET /orders/1
  # GET /orders/1.json
  def show
    # @orderitems = Orderitem.all
    @orderitems = Orderitem.where(order_id: params[:id])
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:order_date, :user_id, :status)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="mainCont">


<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_date %>
    <%= form.datetime_select :order_date %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table id="customers">
  <thead>
    <tr>
      <th>Order Number</th>
      <th>User</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.user.email %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
<div class="mainCont">
<p>
  <strong>Order date:</strong>
  <%= @order.order_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user.email %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<p>
  <strong>Order Id:</strong>
  <%= @order.id %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>
</div>
<br><br>

<div class="mainCont">
  <h1>Items in this order are</h1>
  <table id="customers">
    <% @orderitems.each do |orderitem| %>
     <% @total = 0 %>
    <tr>
      
      <td><%= orderitem.title %></td>
      <td><%= orderitem.quantity %></td>
      <td><%= orderitem.price %></td>
      <% linetotal =(orderitem.quantity * orderitem.price) %>
      <% @total += linetotal %>
     <td>Total price: <%= @total %></td>
      </tr>
    

    
    <% end %>
    
          <tr>
        <% shipping = 20 %>
        <% @grandtotal = shipping + @total %>
        <td>Shipping &euro;20</td>
        <td>Your total today is: &euro;<%= @grandtotal %></td>
        </tr>
  </table>
  </div>
  

  
  <div class="mainCont">
    <a href="/paid/<%= @order.id %>" class="button">Pay now</a>
    </div>