config/routes.rb
Rails.application.routes.draw do
  resources :guitarcats
  resources :categories
  resources :profiles
  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'
  
  
  
  resources :orders do
    resources:orderitems
  end
  
  
  
  
  
  
  
  devise_for :users do
    resources:orders
  end
    
    post '/search' => 'items#search'
    
    
    get '/checkout' => 'cart#createOrder'
  
  
  get 'cart/index'
  resources :items
  root 'static_pages#home'
  
  
  get '/about' =>'static_pages#about'
  get '/help' =>'static_pages#help'
  
  get '/login' => 'user#login'
  
  get '/logout' => 'user#logout'
  
  get '/cart/clear' => 'cart#clearCart'
  
  get '/cart/:id' => 'cart#add'
  
  get '/cart/remove/:id' => 'cart#remove'
  
  get '/cart/decrease/:id' => 'cart#decrease'
  
  get '/paid/:id' => 'static_pages#paid'
  
  get '/category/:title' => 'static_pages#category'
  
  get '/cart' => 'cart#index'
  

  
  # get 'static_pages/home'
  # get 'static_pages/help'
  # get 'static_pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/guitarcat.rb
class Guitarcat < ApplicationRecord
end

app/controllers/guitarcats_controller.rb
class GuitarcatsController < ApplicationController
  before_action :set_guitarcat, only: [:show, :edit, :update, :destroy]

  # GET /guitarcats
  # GET /guitarcats.json
  def index
    @guitarcats = Guitarcat.all
  end

  # GET /guitarcats/1
  # GET /guitarcats/1.json
  def show
  end
  
  
  

  # GET /guitarcats/new
  def new
    @guitarcat = Guitarcat.new
  end

  # GET /guitarcats/1/edit
  def edit
  end

  # POST /guitarcats
  # POST /guitarcats.json
  def create
    @guitarcat = Guitarcat.new(guitarcat_params)

    respond_to do |format|
      if @guitarcat.save
        format.html { redirect_to @guitarcat, notice: 'Guitarcat was successfully created.' }
        format.json { render :show, status: :created, location: @guitarcat }
      else
        format.html { render :new }
        format.json { render json: @guitarcat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guitarcats/1
  # PATCH/PUT /guitarcats/1.json
  def update
    respond_to do |format|
      if @guitarcat.update(guitarcat_params)
        format.html { redirect_to @guitarcat, notice: 'Guitarcat was successfully updated.' }
        format.json { render :show, status: :ok, location: @guitarcat }
      else
        format.html { render :edit }
        format.json { render json: @guitarcat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guitarcats/1
  # DELETE /guitarcats/1.json
  def destroy
    @guitarcat.destroy
    respond_to do |format|
      format.html { redirect_to guitarcats_url, notice: 'Guitarcat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guitarcat
      @guitarcat = Guitarcat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guitarcat_params
      params.require(:guitarcat).permit(:title, :description, :image)
    end
end

app/helpers/guitarcats_helper.rb
module GuitarcatsHelper
end

app/views/guitarcats/_form.html.erb
<%= form_with(model: guitarcat, local: true) do |form| %>
  <% if guitarcat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guitarcat.errors.count, "error") %> prohibited this guitarcat from being saved:</h2>

      <ul>
      <% guitarcat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/guitarcats/edit.html.erb
<h1>Editing Guitarcat</h1>

<%= render 'form', guitarcat: @guitarcat %>

<%= link_to 'Show', @guitarcat %> |
<%= link_to 'Back', guitarcats_path %>

app/views/guitarcats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guitarcats</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guitarcats.each do |guitarcat| %>
      <tr>
        <td><%= guitarcat.title %></td>
        <td><%= guitarcat.description %></td>
        <td><%= guitarcat.image %></td>
        <td><%= link_to 'Show', guitarcat %></td>
        <td><%= link_to 'Edit', edit_guitarcat_path(guitarcat) %></td>
        <td><%= link_to 'Destroy', guitarcat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guitarcat', new_guitarcat_path %>

app/views/guitarcats/new.html.erb
<h1>New Guitarcat</h1>

<%= render 'form', guitarcat: @guitarcat %>

<%= link_to 'Back', guitarcats_path %>

app/views/guitarcats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @guitarcat.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @guitarcat.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @guitarcat.image %>
</p>

<%= link_to 'Edit', edit_guitarcat_path(@guitarcat) %> |
<%= link_to 'Back', guitarcats_path %>