config/routes.rb
Rails.application.routes.draw do
  resources :guitarcats
  resources :categories
  resources :profiles
  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'
  
  
  
  resources :orders do
    resources:orderitems
  end
  
  
  
  
  
  
  
  devise_for :users do
    resources:orders
  end
    
    post '/search' => 'items#search'
    
    
    get '/checkout' => 'cart#createOrder'
  
  
  get 'cart/index'
  resources :items
  root 'static_pages#home'
  
  
  get '/about' =>'static_pages#about'
  get '/help' =>'static_pages#help'
  
  get '/login' => 'user#login'
  
  get '/logout' => 'user#logout'
  
  get '/cart/clear' => 'cart#clearCart'
  
  get '/cart/:id' => 'cart#add'
  
  get '/cart/remove/:id' => 'cart#remove'
  
  get '/cart/decrease/:id' => 'cart#decrease'
  
  get '/paid/:id' => 'static_pages#paid'
  
  get '/category/:title' => 'static_pages#category'
  
  get '/cart' => 'cart#index'
  

  
  # get 'static_pages/home'
  # get 'static_pages/help'
  # get 'static_pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
   def search
      searchterm = "%#{params[:searchbox]}%"
      @items = Item.where("title like ?", searchterm)
      
  end
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category, :brand)
    end
    
   

    
    
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="mainCont">


<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
 
 </div>
 

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

 <div id="itemsContainer">
  
  <h1>Guitars</h1>
     
      <% @items.each do |item| %>
      <div class="itemhols">
       <h1><%= item.title %></h1>
       
       <%= link_to (image_tag item.image_url, :class => "itemholsIm"), item %>
        
       <p>Price <%= number_to_currency(item.price, :unit => "€") %>
       <br>
       
        <br>
        Brand: <%= item.brand %></p>
       
       <p>
         <%= link_to 'Show',  item, :class => "button", :role => "button" %>
         
         <a href="/cart/<%= item.id %>" class="button">Add me to cart</a>
         
         
         <% if session[:login] == 1 %>
         <%= link_to 'Edit',  edit_item_path(item), :class => "button", :role => "button" %>
         <%= link_to 'Destroy',  item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
       <% end %>
       
       
       
       </p>
        
      </div>
    <% end %>
      
</div>

<br>
<%= link_to 'New Item',  new_item_path, :class => "button", :role => "button" %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
<% if @items.length == 0 %>
<div class="mainCont">
    <h2>Unfortunately we do not have this in stock at the moment</h2>
</div>
<% end %>

<br><br>
<div class="mainCont">
    
  
  
     
      <% @items.each do |item| %>
      <div class="itemhols">
       <h1><%= item.title %></h1>
       
       <%= link_to (image_tag item.image_url, :class => "itemholsIm"), item %>
       
      
       
     
         
         
         <% if session[:login] == 1 %>
         <%= link_to 'Edit',  edit_item_path(item), :class => "button", :role => "button" %>
         <%= link_to 'Destroy',  item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
       <% end %>
       
       
       
       </p>
        
      </div>
    <% end %>
      
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div id="itemsContainer">
   <h1><%= @item.title %></h1>
   <%= image_tag @item.image_url, :class => 'welcomIm'  %>
       <h2><%= @item.description %></h1>
   
    <div class="itemhols">
       <p>Price <%= number_to_currency(@item.price, :unit => "€") %>
       <br>
        Category: <%= @item.category %>
        <br>
        Brand: <%= @item.brand %></p>



      <p>
         <%= link_to 'Back',  items_path, :class => "button", :role => "button" %>
         <%= link_to 'Edit',  edit_item_path(@item), :class => "button", :role => "button" %>
         <a href="/cart/<%= @item.id %>" :class="button"> Add Me To Cart</a>
         
       </p>
        
      </div>
   
   
   </div>